In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4, 10.4))  # Range function will not be able to take float values

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# For this we will use arrange function

np.arange(0.4,10.4)

In [5]:
np.arange(0.4,10.4, 0.4)  # Last 0.4 is step size

array([ 0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,
        4.8,  5.2,  5.6,  6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,
        9.2,  9.6, 10. ])

In [6]:
list(np.arange(0.4,10.4, 0.4))

[0.4,
 0.8,
 1.2000000000000002,
 1.6,
 2.0,
 2.4,
 2.8000000000000003,
 3.2,
 3.6,
 4.0,
 4.4,
 4.800000000000001,
 5.200000000000001,
 5.6000000000000005,
 6.000000000000001,
 6.4,
 6.800000000000001,
 7.200000000000001,
 7.6000000000000005,
 8.0,
 8.4,
 8.8,
 9.200000000000001,
 9.600000000000001,
 10.000000000000002]

In [7]:
np.linspace(1,5 ,20)  # It means generate 20 data from 1 to 5 scale

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
np.logspace(1,5, 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [9]:
np.zeros(5)  # It will generate 5 datasets with zero

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))  # It will generate data with 3*4 dimension

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4,2))  # 3 means generate 3d datasets with 4 rows and 2 cols.

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.zeros((3,4,4,2)) # It will generate main 3 matrix and in that there will be 4 matrix of 4 rows and 2 cols.

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
arr = np.ones((3,4))

In [15]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr+5  # It will add 5 in every element

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [17]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [18]:
arr1 = np.eye(5)  # It will give identity matrix in which upper and lower triangular matrix are 0

In [19]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Converting array to dataframe

In [21]:
import pandas as pd

In [22]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [23]:
np.random.rand(2,3)  # It will give random values 

array([[0.82603841, 0.99824137, 0.12158026],
       [0.88092734, 0.59109357, 0.32700978]])

In [24]:
np.random.randn(2,3)  # In this mean will be 0 and std. deviation is 1 i.e. it is standard normal distribution

array([[-0.22993279,  0.43790254, -1.11170615],
       [-1.34925458,  0.47186339,  0.46687508]])

In [25]:
arr2 = np.random.randint(1,5, (3,4))  # Generate data from 1 to 5 with shape 3,4

In [26]:
arr2

array([[4, 3, 1, 2],
       [1, 4, 2, 1],
       [1, 3, 3, 3]])

In [27]:
arr2.size

12

In [28]:
arr2.shape

(3, 4)

In [29]:
# Changing shape

arr2.reshape(2,6)

array([[4, 3, 1, 2, 1, 4],
       [2, 1, 1, 3, 3, 3]])

In [30]:
arr2.reshape(2,2,3)

array([[[4, 3, 1],
        [2, 1, 4]],

       [[2, 1, 1],
        [3, 3, 3]]])

In [31]:
arr1 = np.random.randint(1,10, (5,6))

In [32]:
arr1

array([[9, 3, 4, 9, 6, 5],
       [8, 3, 4, 9, 1, 4],
       [3, 4, 5, 3, 4, 4],
       [6, 6, 2, 9, 3, 4],
       [1, 3, 6, 3, 9, 8]])

In [33]:
#  Values greater than 8 in array

arr1>8

array([[ True, False, False,  True, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False]])

In [34]:
arr1[arr1 > 8]

array([9, 9, 9, 9, 9])

In [35]:
arr1

array([[9, 3, 4, 9, 6, 5],
       [8, 3, 4, 9, 1, 4],
       [3, 4, 5, 3, 4, 4],
       [6, 6, 2, 9, 3, 4],
       [1, 3, 6, 3, 9, 8]])

In [37]:
arr1[0]

array([9, 3, 4, 9, 6, 5])

In [40]:
arr1[0, [0,1]]  # From 0 row give me 0th and 1th dataset

array([9, 3])

In [44]:
arr1[2:4, [2,3]] # Row 2:4 i.e. 2 and 3 and col [2,3]

array([[5, 3],
       [2, 9]])

In [46]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [47]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [48]:
arr2

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [49]:
arr1 + arr2

array([[3, 2, 2],
       [3, 4, 4],
       [2, 3, 3]])

In [50]:
arr1-arr2

array([[-1,  0,  0],
       [ 1,  0,  0],
       [ 0, -1, -1]])

In [52]:
arr1*arr2  # This is multiplication of elements

array([[2, 1, 1],
       [2, 4, 4],
       [1, 2, 2]])

In [54]:
# But matrix multiplication is done by

arr1@arr2

array([[ 4,  5,  5],
       [ 8, 10, 10],
       [ 4,  5,  5]])

In [55]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [2. , 1. , 1. ],
       [1. , 0.5, 0.5]])

# Numpy Broadcasting

In [56]:
arr = np.zeros((3,4))

In [57]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
arr+5  # This is broadcasting it is done to all elements

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [61]:
a = np.array([1,2,3,4])

In [63]:
arr+a  # Th8s will add horizontally

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [64]:
b = np.array([3,4,5])

In [65]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [66]:
# It can not be broadcast of different shape

In [67]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [71]:
# Square root

np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.        ]])

In [73]:
np.exp(arr1) # Exponent func

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 2.71828183]])

In [74]:
np.min(arr1)

1

In [77]:
np.max(arr1)

2